<a href="https://colab.research.google.com/github/MigueXYLO/python/blob/main/02_artificial_neurons_02_OR_dataset_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [1]:
# Uploading the dataset file
from google.colab import files
uploaded = files.upload()

Saving 02_artificial_neurons_02_OR_dataset.csv to 02_artificial_neurons_02_OR_dataset.csv


In [3]:
# Loading the dataset
dataset = np.loadtxt(
'02_artificial_neurons_02_OR_dataset.csv', delimiter=',')
# We will split the array into two arrays by selecting subsets of
# columns using the standard NumPy slice operator “:”.
# The following line selects the first 2 columns, from index 0 to
# index 2 via the slice 0:2.
training_data = dataset[:, 0:2]
# selects the output column (the 3rd variable) via index 2.
target_data = dataset[:, 2]

In [4]:
#Visualizing training data
print(training_data)
print(training_data.shape)
print(len(training_data))
#Visualizing target data
print(target_data)
print(target_data.shape)
print(len(target_data))

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
(4, 2)
4
[0. 1. 1. 1.]
(4,)
4


In [5]:
# Defining the model
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

In [6]:
#Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.25),loss='MSE',metrics=['accuracy'])

In [7]:
# Training the model on the dataset
model.fit(training_data, target_data, epochs=100, batch_size=1)

Epoch 1/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3944 - accuracy: 0.0000e+00
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3323 - accuracy: 0.0000e+00
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 0.2788 - accuracy: 0.2500
Epoch 4/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2378 - accuracy: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2111 - accuracy: 0.7500
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 0.1936 - accuracy: 0.7500
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 0.1814 - accuracy: 0.7500
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 0.1733 - accuracy: 0.7500
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 0.1666 - accuracy: 0.7500
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.1614 - accuracy: 0.7500
Epoch 11/100
4/4 [===

In [8]:
scores = model.evaluate(training_data, target_data)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print (model.predict(training_data).round())

1/1 [==============================] - 0s 188ms/step - loss: 0.0415 - accuracy: 1.0000

accuracy: 100.00%
1/1 [==============================] - 0s 62ms/step
[[0.]
 [1.]
 [1.]
 [1.]]


In [9]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[2.2794952],
        [2.289717 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([-0.7584496], dtype=float32)>]

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [11]:
model.save('/content/drive/MyDrive/models/02_artificial_neurons_01_OR_model.h5')


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [12]:
from tensorflow import keras
loaded_model = keras.models.load_model('/content/drive/MyDrive/models/02_artificial_neurons_01_OR_model.h5')
print (loaded_model.predict(training_data).round())

1/1 [==============================] - 0s 33ms/step
[[0.]
 [1.]
 [1.]
 [1.]]
