<a href="https://colab.research.google.com/github/MigueXYLO/python/blob/main/02_artificial_neurons_02_AND_dataset_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [9]:
# Uploading the dataset file
from google.colab import files
uploaded = files.upload()

Saving 02_artificial_neurons_02_AND_dataset.csv to 02_artificial_neurons_02_AND_dataset.csv


In [12]:
# Loading the dataset
dataset = np.loadtxt(
'02_artificial_neurons_02_AND_dataset.csv', delimiter=',')
# We will split the array into two arrays by selecting subsets of
# columns using the standard NumPy slice operator “:”.
# The following line selects the first 2 columns, from index 0 to
# index 2 via the slice 0:2.
training_data = dataset[:, 0:2]
# selects the output column (the 3rd variable) via index 2.
target_data = dataset[:, 2]

In [20]:
#Visualizing training data
print(training_data)
print(training_data.shape)
print(len(training_data))
#Visualizing target data
print(target_data)
print(target_data.shape)
print(len(target_data))

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
(4, 2)
4
[0. 0. 0. 1.]
(4,)
4


In [13]:
# Defining the model
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

In [14]:
#Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.25),loss='MSE',metrics=['accuracy'])

In [15]:
# Training the model on the dataset
model.fit(training_data, target_data, epochs=100, batch_size=1)

Epoch 1/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2983 - accuracy: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2926 - accuracy: 0.7500
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2875 - accuracy: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2826 - accuracy: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2784 - accuracy: 0.7500
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2748 - accuracy: 0.7500
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2714 - accuracy: 0.7500
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2681 - accuracy: 0.7500
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2650 - accuracy: 0.7500
Epoch 10/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2625 - accuracy: 0.7500
Epoch 11/100
4/4 [===========

In [21]:
scores = model.evaluate(training_data, target_data)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print (model.predict(training_data).round())

1/1 [==============================] - 0s 27ms/step - loss: 0.0732 - accuracy: 1.0000

accuracy: 100.00%
1/1 [==============================] - 0s 20ms/step
[[0.]
 [0.]
 [0.]
 [1.]]


In [22]:
model.weights

[<tf.Variable 'dense_1/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[1.5227345],
        [1.5141405]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-2.4618127], dtype=float32)>]

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [24]:
model.save('/content/drive/MyDrive/models/02_artificial_neurons_01_AND_model.h5')


In [25]:
from tensorflow import keras
loaded_model = keras.models.load_model('/content/drive/MyDrive/models/02_artificial_neurons_01_AND_model.h5')
print (loaded_model.predict(training_data).round())

1/1 [==============================] - 0s 54ms/step
[[0.]
 [0.]
 [0.]
 [1.]]
