<a href="https://colab.research.google.com/github/MigueXYLO/python/blob/main/02_artificial_neurons_01_AND.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [19]:
# Defining the dataset
training_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], "float32")
target_data = np.array([[0], [0], [0], [1]], "float32")

In [20]:
# Defining the model
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

In [21]:
#Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.25),loss='MSE',metrics=['accuracy'])

In [22]:
# Training the model on the dataset
model.fit(training_data, target_data, epochs=100, batch_size=1)

Epoch 1/100
4/4 [==============================] - 0s 6ms/step - loss: 0.2761 - accuracy: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 0.2682 - accuracy: 0.7500
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2613 - accuracy: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2538 - accuracy: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2483 - accuracy: 0.7500
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2431 - accuracy: 0.7500
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2375 - accuracy: 0.7500
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2328 - accuracy: 0.7500
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2280 - accuracy: 0.7500
Epoch 10/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2234 - accuracy: 0.7500
Epoch 11/100
4/4 [===========

In [23]:
scores = model.evaluate(training_data, target_data)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print (model.predict(training_data).round())

1/1 [==============================] - 0s 103ms/step - loss: 0.0619 - accuracy: 1.0000

accuracy: 100.00%
1/1 [==============================] - 0s 40ms/step
[[0.]
 [0.]
 [0.]
 [1.]]


In [24]:
model.weights

[<tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[1.7698705],
        [1.7783811]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([-2.7777576], dtype=float32)>]

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [26]:
model.save('/content/drive/MyDrive/models/02_artificial_neurons_01_AND_model.h5')


In [27]:
from tensorflow import keras
loaded_model = keras.models.load_model('/content/drive/MyDrive/models/02_artificial_neurons_01_AND_model.h5')
print (loaded_model.predict(training_data).round())

1/1 [==============================] - 0s 41ms/step
[[0.]
 [0.]
 [0.]
 [1.]]
